# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amajm/CS100Project/spring-2019-assignment-cs100-abdullah-emily

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amajm/CS100Project/spring-2019-assignment-cs100-abdullah-emily

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amajm/CS100Project/spring-2019-assignment-cs100-abdullah-emily/CMakeFiles /home/amajm/CS100Project/spring-2019-assignment-cs100-abdullah-emily/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amajm/CS100Project/spring-2019-assignment-cs100-abdullah-emily/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Project

# Build rule for target.
Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project
.PHONY : Project

# fast build rule for target.
Project/fast:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/build
.PHONY : Project/fast

Source/Add.o: Source/Add.cpp.o

.PHONY : Source/Add.o

# target to build an object file
Source/Add.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Add.cpp.o
.PHONY : Source/Add.cpp.o

Source/Add.i: Source/Add.cpp.i

.PHONY : Source/Add.i

# target to preprocess a source file
Source/Add.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Add.cpp.i
.PHONY : Source/Add.cpp.i

Source/Add.s: Source/Add.cpp.s

.PHONY : Source/Add.s

# target to generate assembly for a file
Source/Add.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Add.cpp.s
.PHONY : Source/Add.cpp.s

Source/Command.o: Source/Command.cpp.o

.PHONY : Source/Command.o

# target to build an object file
Source/Command.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Command.cpp.o
.PHONY : Source/Command.cpp.o

Source/Command.i: Source/Command.cpp.i

.PHONY : Source/Command.i

# target to preprocess a source file
Source/Command.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Command.cpp.i
.PHONY : Source/Command.cpp.i

Source/Command.s: Source/Command.cpp.s

.PHONY : Source/Command.s

# target to generate assembly for a file
Source/Command.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Command.cpp.s
.PHONY : Source/Command.cpp.s

Source/Or.o: Source/Or.cpp.o

.PHONY : Source/Or.o

# target to build an object file
Source/Or.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Or.cpp.o
.PHONY : Source/Or.cpp.o

Source/Or.i: Source/Or.cpp.i

.PHONY : Source/Or.i

# target to preprocess a source file
Source/Or.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Or.cpp.i
.PHONY : Source/Or.cpp.i

Source/Or.s: Source/Or.cpp.s

.PHONY : Source/Or.s

# target to generate assembly for a file
Source/Or.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Or.cpp.s
.PHONY : Source/Or.cpp.s

Source/Parser.o: Source/Parser.cpp.o

.PHONY : Source/Parser.o

# target to build an object file
Source/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Parser.cpp.o
.PHONY : Source/Parser.cpp.o

Source/Parser.i: Source/Parser.cpp.i

.PHONY : Source/Parser.i

# target to preprocess a source file
Source/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Parser.cpp.i
.PHONY : Source/Parser.cpp.i

Source/Parser.s: Source/Parser.cpp.s

.PHONY : Source/Parser.s

# target to generate assembly for a file
Source/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Parser.cpp.s
.PHONY : Source/Parser.cpp.s

Source/Semi.o: Source/Semi.cpp.o

.PHONY : Source/Semi.o

# target to build an object file
Source/Semi.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Semi.cpp.o
.PHONY : Source/Semi.cpp.o

Source/Semi.i: Source/Semi.cpp.i

.PHONY : Source/Semi.i

# target to preprocess a source file
Source/Semi.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Semi.cpp.i
.PHONY : Source/Semi.cpp.i

Source/Semi.s: Source/Semi.cpp.s

.PHONY : Source/Semi.s

# target to generate assembly for a file
Source/Semi.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/Semi.cpp.s
.PHONY : Source/Semi.cpp.s

Source/main.o: Source/main.cpp.o

.PHONY : Source/main.o

# target to build an object file
Source/main.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/main.cpp.o
.PHONY : Source/main.cpp.o

Source/main.i: Source/main.cpp.i

.PHONY : Source/main.i

# target to preprocess a source file
Source/main.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/main.cpp.i
.PHONY : Source/main.cpp.i

Source/main.s: Source/main.cpp.s

.PHONY : Source/main.s

# target to generate assembly for a file
Source/main.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Source/main.cpp.s
.PHONY : Source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... Project"
	@echo "... rebuild_cache"
	@echo "... Source/Add.o"
	@echo "... Source/Add.i"
	@echo "... Source/Add.s"
	@echo "... Source/Command.o"
	@echo "... Source/Command.i"
	@echo "... Source/Command.s"
	@echo "... Source/Or.o"
	@echo "... Source/Or.i"
	@echo "... Source/Or.s"
	@echo "... Source/Parser.o"
	@echo "... Source/Parser.i"
	@echo "... Source/Parser.s"
	@echo "... Source/Semi.o"
	@echo "... Source/Semi.i"
	@echo "... Source/Semi.s"
	@echo "... Source/main.o"
	@echo "... Source/main.i"
	@echo "... Source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

